spec:
  template:
    spec:
      containers:
        -
          resources:
           requests:
             cpu: "0.2"
             memory: 512Mi
           limits:
             cpu: "1.0"
             memory: 512Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
